Fix Werror=maybe-uninitialized for GCC7
Fix the issue with gcc 7 and :
In function ‘lookup_dev_manufacturer_serial_part’:
src/lib/device_utilities.c:399:27:
error: ‘p_devices’ may be used uninitialized in this function
[-Werror=maybe-uninitialized]
  struct device_discovery *p_devices;
                             ^~~~~~~~~
                             compilation terminated due to -Wfatal-errors.

Signed-off-by: VictorRodriguez <victor.rodriguez.bahena@intel.com>